### ISSUE TITLE
RequireJS 2.0 support and other improvements

### ISSUE THREAD

**Issue by ruimarinho** [hearsayit/HearsayRequireJSBundle#12]
With the release of RequireJS 2.0, it has become even more simple to manage module dependencies. The current version of `HearsayRequireJSBundle` does not work with the most recent release of RequireJS because it needs some work to get this upgrade rolling (see [upgrade notes](https://github.com/jrburke/requirejs/wiki/Upgrading-to-RequireJS-2.0)). Above are some notes from a debugging session, although I'm not sure what's the best way to fix them. I'll be more than happy if we can brainstorm on possible solutions for these issues:
- `baseUrl` does not work well with `data-main`, since this attribute not requires a module. When used in conjunction with `use_controller` at true and Assetic, it will report a 404 since the `asset_url` expects to have a `.js` extension but RequireJS automatically removes it now (see [here](https://github.com/jrburke/requirejs/blob/master/require.js#L1934)). This means assetic won't be able to serve that file (e.g.  `GET http://project.dev/app_dev.php/js/92bcd61_documents_1`)

An alternative would be generating a dynamic config file and calling `require.config` instead of using the `data-main` attribute. The disadvantage of this method is that we would need a custom route for this and a real file would have to be generated for production minification.

Example:

``` js
require.config({
  deps: [ {{ real_module_to_load }} ],

  paths: { ... }
  }
});
```

Assetic would have to know about this file and the deps it loads so that the `r.js` optimizer can kick in.
- `paths`: one of the best features of `paths` configuration is the possibility of aliasing long lib path names. Although the docs say this is possible using the `config.yml` directive, it does not appear to work well with Assetic, due to incorrect URL resolution. `alpha: '%kernel.root_dir%/../src/MyProject/DocumentBundle/Resources/public/js/vendor/alpha/alpha.js'` does not appear to be resolved when `require(['alpha'])`is called.
- `require_js_src` is prepared to load a CDN version of RequireJS only - not local versions.
- `shims`: another great addition of RequireJS is the support to use shims, effectively wrapping non-AMD libs such as Backbone, Lodash, jQuery Plugins, etc. This is fundamental since we no longer need to use custom versions with our own `define` patches.

**Comment by kmontag** [comment]
Currently looking into the baseUrl and paths bugs :)

As for the RequireJS src, for now you can load a local version by specifying an alternate `initialize_template` which extends `'HearsayRequireJSBundle::initialize.html.twig'` and overrides the `src` block.  That's something of a hack, though - currently my thought is to allow specifying either a URL or a _template name_ as the `src` config option.  If a template name is given, it'll be rendered to generate the src URL - that way you can use Assetic or whatever to process a local file, and spit out an asset URL to use for the RequireJS src.

Shim is also high priority - currently I'm thinking it should just live in the bundle config, similar to `paths`.  Though in general, as the set of available RequireJS options gets more complex, I'm starting to wonder if there's a good way for the bundle to support more generic configuration setups, particularly for optimization.  Writing the optimizer as an Assetic filter introduces some tricky inconsistencies with the "standard" methods of optimizing a RequireJS project, mainly because it forces optimization to happen file-at-a-time rather than directory-at-a-time.  Any thoughts on a better configuration API are certainly welcome :)

**Comment by ruimarinho** [comment]
Correct, I overwrote the `initialize.html.twig` template, but the integration with Assetic with a custom route could be a better option. 

I think `shims` fit on the bundle config too, although it would be optimal to dynamically generate a `js` config file and then dump it for Assetic processing. This way we can take advantage of some bundle processing, but still being able to tweak the settings without having to create more bundle configuration options. In a certain way, you can already do this with the initialize template, but probably not as cleanly :)

I wonder if we can run the `r.js` optimizer without Assetic - possibly using a Twig tag (`{% requirejs %}`) - that way we could take advantage of all the features of this build tool (or others, such as [grunt](https://github.com/cowboy/grunt)). Not sure if this is reinventing the wheel though...

**Comment by pliniocsfernandes** [comment]
Any updates on this one?

**Comment by adamborowski** [comment]
in config.yml write in requirejs section:

```
require_js_src: /path/to/require.min.js
```

**Comment by ihortymoshenko** [comment]
I have some thoughts after reading this issue. I think possible to implement the ability to customize configuration options for each bundle using some namespaces which are reflect the bundle names. In addition, specify some global configuration options which will be applied to each bundle with the ability to override the latter at the bundle level configuration. What do you think?

**Comment by ihortymoshenko** [comment]
@ruimarinho, at this moment we don't have only the ability to specify a local path to the `RequireJS` via the `require_js_src`. Can you confirm? I'll add the last and close this issue. Thanks!

**Comment by ihortymoshenko** [comment]
I've added the ability to specify the local path to the `RequireJS`. If you have any questions, create a new issue please. Thanks!
